{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "visus = 9"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from aiohttp import web\n",
    "import asyncio\n",
    "\n",
    "import nest_asyncio\n",
    "nest_asyncio.apply()\n",
    "\n",
    "visus = 9\n",
    "\n",
    "routes = web.RouteTableDef()\n",
    "\n",
    "@routes.get('/')\n",
    "async def tile(request):\n",
    "    return web.Response(text=f\"Visus={visus}\")\n",
    "\n",
    "app = web.Application()\n",
    "app.add_routes(routes)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#web.run_app(app)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======== Running on http://0.0.0.0:8080 ========\n",
      "(Press CTRL+C to quit)\n"
     ]
    }
   ],
   "source": [
    "async def run():\n",
    "    web.run_app(app)\n",
    "\n",
    "try:\n",
    "    task = asyncio.create_task(run())\n",
    "except asyncio.CancelledError:\n",
    "        print('canceled')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid HTTP version'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "  File \"aiohttp/_http_parser.pyx\", line 650, in aiohttp._http_parser.cb_on_header_value\n",
      "aiohttp.http_exceptions.LineTooLong: 400, message='Got more than 8190 bytes (10002) when reading Header value is too long.'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadStatusLine: invalid HTTP method\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='LF character expected'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='LF character expected'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid character in header'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid character in header'\n",
      "Error handling request\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/yarden/miniconda3/envs/visus/lib/python3.7/site-packages/aiohttp/web_protocol.py\", line 275, in data_received\n",
      "    messages, upgraded, tail = self._request_parser.feed_data(data)\n",
      "  File \"aiohttp/_http_parser.pyx\", line 523, in aiohttp._http_parser.HttpParser.feed_data\n",
      "aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'\n"
     ]
    }
   ],
   "source": [
    "visus = 20"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "task.cancel()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Task pending coro=<run() running at <ipython-input-4-5c61aae399a1>:2>>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "task"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "task.cancel()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Task cancelling coro=<run() running at <ipython-input-4-5c61aae399a1>:2>>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "task"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
